export interface ExportReportResponse9015 {
    branch: string,
    branchTaxNumber: string,
    branchName: string,
    grossCode: string,
    yield: string,
    taxBaseMonth: string,
    taxValueMonth: string,
    taxBaseMonthSuspended: string,
    taxValueMonthSuspended: string,
    taxBaseBiweekly: string,
    taxValueBiweekly: string,
    taxBaseBiweeklySuspended: string,
    taxValueBiweeklySuspended: string,
    taxBaseDecennial: string,
    taxValueDecennial: string,
    taxBaseDecennialSuspended: string,
    taxValueDecennialSuspended: string,
    taxBaseWeekly: string,
    taxValueWeekly: string,
    taxBaseWeeklySuspended: string,
    taxValueWeeklySuspended: string,
    taxBaseDaily: string,
    taxValueDaily: string,
    taxBaseDailySuspended: string,
    taxValueDailySuspended: string,
}